services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database-1.cx08k2wim7je.ap-northeast-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_USERNAME: superhsk00
      DB_PASSWORD: nexonhsk00
      REDIS_HOST: master.steam-cache-cluster.vx1gza.apn2.cache.amazonaws.com
      REDIS_PORT: 6379
      JWT_SECRET: YW5kcmV3MDI3MzkyNzg2Mjk0NzQ2Mjk1NjUyOTM3NjQ5NQ==
      MAIL_USERNAME: superhsk00@gmail.com
      MAIL_PASSWORD: kvaelytnqmpofrfy
    networks:
      - steam-network

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - steam-network

networks:
  steam-network:

